# Generated by Django 4.1 on 2023-04-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auth_delete_publications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth',
            options={'ordering': [], 'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
        migrations.AlterField(
            model_name='auth',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Електронний адрес'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='nickname',
            field=models.CharField(max_length=255, verbose_name='Нікнейм'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
