# Generated by Django 4.1 on 2023-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_auth_options_alter_auth_date_alter_auth_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Опис')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('views', models.IntegerField(verbose_name='Кількість переглядів')),
                ('likes', models.IntegerField(verbose_name='Кількість вподобайок')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main/img/server', verbose_name='Прикріпити зображення')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': [],
            },
        ),
    ]
