# Generated by Django 4.1 on 2023-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to='main/img/server', verbose_name='Прикріпити зображення'),
        ),
    ]
